
package ru.mil.smb.wsdl.data;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2015-09-10T10:04:10.102+03:00
 * Generated source version: 3.0.6
 * 
 */
public final class MoSoapGateway_MoSoapGatewaySoap11_Client {

    private static final QName SERVICE_NAME = new QName("http://smb.mil.ru/wsdl/data", "moSoapGatewayService");

    private MoSoapGateway_MoSoapGatewaySoap11_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = MoSoapGatewayService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MoSoapGatewayService ss = new MoSoapGatewayService(wsdlURL, SERVICE_NAME);
        MoSoapGateway port = ss.getMoSoapGatewaySoap11();



        
        {
        System.out.println("Invoking getRSAKey...");
        ru.mil.smb.wsdl.data.GetRSAKeyRequest _getRSAKey_getRSAKeyRequest = null;
        ru.mil.smb.wsdl.data.GetRSAKeyResponse _getRSAKey__return = port.getRSAKey(_getRSAKey_getRSAKeyRequest);
        System.out.println("getRSAKey.result=" + _getRSAKey__return);


        }
        {
        System.out.println("Invoking sendRequestConfirmation...");
        ru.mil.smb.wsdl.data.SendRequestConfirmationRequest _sendRequestConfirmation_sendRequestConfirmationRequest = null;
        ru.mil.smb.wsdl.data.SendRequestConfirmationResponse _sendRequestConfirmation__return = port.sendRequestConfirmation(_sendRequestConfirmation_sendRequestConfirmationRequest);
        System.out.println("sendRequestConfirmation.result=" + _sendRequestConfirmation__return);


        }
        {
        System.out.println("Invoking startSession...");
        ru.mil.smb.wsdl.data.StartSessionRequest _startSession_startSessionRequest = null;
        ru.mil.smb.wsdl.data.StartSessionResponse _startSession__return = port.startSession(_startSession_startSessionRequest);
        System.out.println("startSession.result=" + _startSession__return);


        }
        {
        System.out.println("Invoking cancelSession...");
        ru.mil.smb.wsdl.data.CancelSessionRequest _cancelSession_cancelSessionRequest = null;
        ru.mil.smb.wsdl.data.CancelSessionResponse _cancelSession__return = port.cancelSession(_cancelSession_cancelSessionRequest);
        System.out.println("cancelSession.result=" + _cancelSession__return);


        }
        {
        System.out.println("Invoking sendFileConfirmation...");
        ru.mil.smb.wsdl.data.SendFileConfirmationRequest _sendFileConfirmation_sendFileConfirmationRequest = null;
        ru.mil.smb.wsdl.data.SendFileConfirmationResponse _sendFileConfirmation__return = port.sendFileConfirmation(_sendFileConfirmation_sendFileConfirmationRequest);
        System.out.println("sendFileConfirmation.result=" + _sendFileConfirmation__return);


        }

        System.exit(0);
    }

}
