package ru.mil.smb.wsdl.data;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.6
 * 2015-09-10T10:04:10.209+03:00
 * Generated source version: 3.0.6
 * 
 */
@WebService(targetNamespace = "http://smb.mil.ru/wsdl/data", name = "moSoapGateway")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface MoSoapGateway {

    @WebMethod(operationName = "GetRSAKey")
    @WebResult(name = "GetRSAKeyResponse", targetNamespace = "http://smb.mil.ru/wsdl/data", partName = "GetRSAKeyResponse")
    public GetRSAKeyResponse getRSAKey(
        @WebParam(partName = "GetRSAKeyRequest", name = "GetRSAKeyRequest", targetNamespace = "http://smb.mil.ru/wsdl/data")
        GetRSAKeyRequest getRSAKeyRequest
    );

    @WebMethod(operationName = "SendRequestConfirmation")
    @WebResult(name = "SendRequestConfirmationResponse", targetNamespace = "http://smb.mil.ru/wsdl/data", partName = "SendRequestConfirmationResponse")
    public SendRequestConfirmationResponse sendRequestConfirmation(
        @WebParam(partName = "SendRequestConfirmationRequest", name = "SendRequestConfirmationRequest", targetNamespace = "http://smb.mil.ru/wsdl/data")
        SendRequestConfirmationRequest sendRequestConfirmationRequest
    );

    @WebMethod(operationName = "StartSession")
    @WebResult(name = "StartSessionResponse", targetNamespace = "http://smb.mil.ru/wsdl/data", partName = "StartSessionResponse")
    public StartSessionResponse startSession(
        @WebParam(partName = "StartSessionRequest", name = "StartSessionRequest", targetNamespace = "http://smb.mil.ru/wsdl/data")
        StartSessionRequest startSessionRequest
    );

    @WebMethod(operationName = "CancelSession")
    @WebResult(name = "CancelSessionResponse", targetNamespace = "http://smb.mil.ru/wsdl/data", partName = "CancelSessionResponse")
    public CancelSessionResponse cancelSession(
        @WebParam(partName = "CancelSessionRequest", name = "CancelSessionRequest", targetNamespace = "http://smb.mil.ru/wsdl/data")
        CancelSessionRequest cancelSessionRequest
    );

    @WebMethod(operationName = "SendFileConfirmation")
    @WebResult(name = "SendFileConfirmationResponse", targetNamespace = "http://smb.mil.ru/wsdl/data", partName = "SendFileConfirmationResponse")
    public SendFileConfirmationResponse sendFileConfirmation(
        @WebParam(partName = "SendFileConfirmationRequest", name = "SendFileConfirmationRequest", targetNamespace = "http://smb.mil.ru/wsdl/data")
        SendFileConfirmationRequest sendFileConfirmationRequest
    );
}
